blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/wax-office-of-inspector-general/wax-developer/discussions
    about: Ask questions and discuss with other community members
